from pathlib import Path
import json

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from train_models import (
    build_models,
    load_modeling_data,
    split_features_target,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]

REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

GRADIENT_FEATURE_IMPORTANCE_PATH = REPORTS_DIR / "gradient_boosting_feature_importance.csv"
LOGISTIC_COEFFICIENTS_PATH = REPORTS_DIR / "logistic_regression_coefficients.csv"

PREDICTIVE_MODEL_NAME = "gradient_boosting"
INTERPRETATION_MODEL_NAME = "logistic_regression"


def clean_feature_name(feature_name: str) -> str:
    """
    Clean feature names generated by ColumnTransformer and OneHotEncoder.
    """
    cleaned_name = feature_name

    prefixes = [
        "numeric__",
        "categorical__",
    ]

    for prefix in prefixes:
        cleaned_name = cleaned_name.replace(prefix, "")

    return cleaned_name


def infer_feature_group(feature_name: str) -> str:
    """
    Infer transformed feature group.
    """
    if feature_name.startswith("numeric__"):
        return "numeric"
    if feature_name.startswith("categorical__"):
        return "categorical"

    return "unknown"


def load_training_inputs() -> tuple[pd.DataFrame, pd.Series, dict]:
    """
    Load modeling data and return train features, target, and feature groups.
    """
    train_data, validation_data, feature_groups = load_modeling_data()

    X_train, y_train, _, _ = split_features_target(
        train_data=train_data,
        validation_data=validation_data,
        feature_groups=feature_groups,
    )

    return X_train, y_train, feature_groups


def train_interpretation_models(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    feature_groups: dict,
) -> tuple[object, object]:
    """
    Train Gradient Boosting and Logistic Regression for interpretation outputs.
    """
    models = build_models(feature_groups)

    gradient_model = models[PREDICTIVE_MODEL_NAME]
    logistic_model = models[INTERPRETATION_MODEL_NAME]

    gradient_model.fit(X_train, y_train)
    logistic_model.fit(X_train, y_train)

    return gradient_model, logistic_model


def extract_gradient_boosting_importance(model: object) -> pd.DataFrame:
    """
    Extract feature importance from Gradient Boosting pipeline.
    """
    preprocessor = model.named_steps["preprocessor"]
    classifier = model.named_steps["model"]

    feature_names = preprocessor.get_feature_names_out()
    importances = classifier.feature_importances_

    importance_df = pd.DataFrame(
        {
            "raw_feature_name": feature_names,
            "feature": [clean_feature_name(name) for name in feature_names],
            "feature_group": [infer_feature_group(name) for name in feature_names],
            "importance": importances,
        }
    )

    importance_df = (
        importance_df
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )

    return importance_df


def extract_logistic_coefficients(model: object) -> pd.DataFrame:
    """
    Extract Logistic Regression coefficients.
    """
    preprocessor = model.named_steps["preprocessor"]
    classifier = model.named_steps["model"]

    feature_names = preprocessor.get_feature_names_out()
    coefficients = classifier.coef_[0]

    coefficients_df = pd.DataFrame(
        {
            "raw_feature_name": feature_names,
            "feature": [clean_feature_name(name) for name in feature_names],
            "feature_group": [infer_feature_group(name) for name in feature_names],
            "coefficient": coefficients,
        }
    )

    coefficients_df["absolute_coefficient"] = coefficients_df["coefficient"].abs()
    coefficients_df["odds_ratio"] = np.exp(coefficients_df["coefficient"])

    coefficients_df = (
        coefficients_df
        .sort_values("absolute_coefficient", ascending=False)
        .reset_index(drop=True)
    )

    return coefficients_df


def save_tables(
    importance_df: pd.DataFrame,
    coefficients_df: pd.DataFrame,
) -> None:
    """
    Save interpretation tables.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    importance_df.to_csv(GRADIENT_FEATURE_IMPORTANCE_PATH, index=False)
    coefficients_df.to_csv(LOGISTIC_COEFFICIENTS_PATH, index=False)

    print("\nSaved interpretation tables")
    print("-" * 80)
    print(f"Gradient Boosting feature importance: {GRADIENT_FEATURE_IMPORTANCE_PATH}")
    print(f"Logistic Regression coefficients: {LOGISTIC_COEFFICIENTS_PATH}")


def save_figures(
    importance_df: pd.DataFrame,
    coefficients_df: pd.DataFrame,
) -> None:
    """
    Save interpretation figures.
    """
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    sns.set_theme(style="whitegrid")

    top_importance = importance_df.head(20).copy()

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_importance,
        x="importance",
        y="feature",
    )
    plt.title("Top 20 Gradient Boosting Feature Importances")
    plt.xlabel("Feature Importance")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_gradient_boosting_feature_importance.png", dpi=300)
    plt.close()

    top_positive = (
        coefficients_df
        .sort_values("coefficient", ascending=False)
        .head(20)
        .copy()
    )

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_positive,
        x="coefficient",
        y="feature",
    )
    plt.title("Top 20 Positive Logistic Regression Coefficients")
    plt.xlabel("Coefficient")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_positive_logistic_coefficients.png", dpi=300)
    plt.close()

    top_negative = (
        coefficients_df
        .sort_values("coefficient", ascending=True)
        .head(20)
        .copy()
    )

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_negative,
        x="coefficient",
        y="feature",
    )
    plt.title("Top 20 Negative Logistic Regression Coefficients")
    plt.xlabel("Coefficient")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_negative_logistic_coefficients.png", dpi=300)
    plt.close()

    print("\nSaved interpretation figures")
    print("-" * 80)
    print(f"Feature importance: {FIGURES_DIR / 'top_gradient_boosting_feature_importance.png'}")
    print(f"Positive coefficients: {FIGURES_DIR / 'top_positive_logistic_coefficients.png'}")
    print(f"Negative coefficients: {FIGURES_DIR / 'top_negative_logistic_coefficients.png'}")


def print_interpretation_summary(
    importance_df: pd.DataFrame,
    coefficients_df: pd.DataFrame,
) -> None:
    """
    Print interpretation summary.
    """
    print("=" * 80)
    print("CHURN MODEL INTERPRETATION")
    print("=" * 80)

    print("\nImportant note")
    print(
        "Gradient Boosting importances show which variables contribute most to prediction, "
        "but they do not show direction. Logistic Regression coefficients provide directional "
        "associations, but they should not be interpreted as causal effects."
    )

    print("\nTop 15 Gradient Boosting feature importances")
    print(
        importance_df.head(15)[
            ["feature", "feature_group", "importance"]
        ].round(4)
    )

    print("\nTop 15 positive Logistic Regression coefficients")
    print(
        coefficients_df
        .sort_values("coefficient", ascending=False)
        .head(15)[
            ["feature", "feature_group", "coefficient", "odds_ratio"]
        ].round(4)
    )

    print("\nTop 15 negative Logistic Regression coefficients")
    print(
        coefficients_df
        .sort_values("coefficient", ascending=True)
        .head(15)[
            ["feature", "feature_group", "coefficient", "odds_ratio"]
        ].round(4)
    )


if __name__ == "__main__":
    X_train, y_train, feature_groups = load_training_inputs()

    gradient_model, logistic_model = train_interpretation_models(
        X_train=X_train,
        y_train=y_train,
        feature_groups=feature_groups,
    )

    gradient_importance = extract_gradient_boosting_importance(gradient_model)
    logistic_coefficients = extract_logistic_coefficients(logistic_model)

    print_interpretation_summary(
        importance_df=gradient_importance,
        coefficients_df=logistic_coefficients,
    )

    save_tables(
        importance_df=gradient_importance,
        coefficients_df=logistic_coefficients,
    )

    save_figures(
        importance_df=gradient_importance,
        coefficients_df=logistic_coefficients,
    )