from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]

REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

VALIDATION_PREDICTIONS_PATH = REPORTS_DIR / "validation_predictions.csv"
THRESHOLD_ANALYSIS_PATH = REPORTS_DIR / "threshold_analysis.csv"
THRESHOLD_RECOMMENDATION_PATH = REPORTS_DIR / "threshold_recommendation.csv"

SELECTED_MODEL = "gradient_boosting"


def load_validation_predictions() -> pd.DataFrame:
    """
    Load validation predictions generated by train_models.py.
    """
    if not VALIDATION_PREDICTIONS_PATH.exists():
        raise FileNotFoundError(
            f"Validation predictions not found at {VALIDATION_PREDICTIONS_PATH}. "
            "Run 'python src/train_models.py' first."
        )

    return pd.read_csv(VALIDATION_PREDICTIONS_PATH)


def evaluate_thresholds(
    predictions: pd.DataFrame,
    model_name: str = SELECTED_MODEL,
) -> pd.DataFrame:
    """
    Evaluate classification metrics across multiple probability thresholds.
    """
    model_predictions = predictions[predictions["model"] == model_name].copy()

    if model_predictions.empty:
        available_models = predictions["model"].unique().tolist()
        raise ValueError(
            f"Model '{model_name}' not found. Available models: {available_models}"
        )

    y_true = model_predictions["actual"]
    y_proba = model_predictions["predicted_probability"]

    thresholds = np.arange(0.10, 0.91, 0.01)

    results = []

    for threshold in thresholds:
        y_pred = (y_proba >= threshold).astype(int)

        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

        results.append(
            {
                "model": model_name,
                "threshold": threshold,
                "accuracy": accuracy_score(y_true, y_pred),
                "precision": precision_score(y_true, y_pred, zero_division=0),
                "recall": recall_score(y_true, y_pred, zero_division=0),
                "f1": f1_score(y_true, y_pred, zero_division=0),
                "true_negatives": tn,
                "false_positives": fp,
                "false_negatives": fn,
                "true_positives": tp,
                "customers_flagged": tp + fp,
                "churners_captured": tp,
                "churners_missed": fn,
            }
        )

    return pd.DataFrame(results)


def select_thresholds(threshold_results: pd.DataFrame) -> pd.DataFrame:
    """
    Select recommended thresholds for different business strategies.
    """
    best_f1_row = threshold_results.loc[
        threshold_results["f1"].idxmax()
    ].copy()

    high_recall_candidates = threshold_results[
        threshold_results["recall"] >= 0.75
    ].copy()

    if not high_recall_candidates.empty:
        high_recall_row = high_recall_candidates.sort_values(
            ["precision", "f1"],
            ascending=False,
        ).iloc[0].copy()
    else:
        high_recall_row = threshold_results.loc[
            threshold_results["recall"].idxmax()
        ].copy()

    high_precision_candidates = threshold_results[
        threshold_results["precision"] >= 0.70
    ].copy()

    if not high_precision_candidates.empty:
        high_precision_row = high_precision_candidates.sort_values(
            ["recall", "f1"],
            ascending=False,
        ).iloc[0].copy()
    else:
        high_precision_row = threshold_results.loc[
            threshold_results["precision"].idxmax()
        ].copy()

    recommendations = pd.DataFrame(
        [
            {
                "strategy": "balanced_f1",
                **best_f1_row.to_dict(),
                "business_meaning": (
                    "Best balance between precision and recall."
                ),
            },
            {
                "strategy": "retention_recall",
                **high_recall_row.to_dict(),
                "business_meaning": (
                    "Prioritizes capturing churners, accepting more false positives."
                ),
            },
            {
                "strategy": "efficient_precision",
                **high_precision_row.to_dict(),
                "business_meaning": (
                    "Prioritizes contacting fewer customers with higher churn probability."
                ),
            },
        ]
    )

    return recommendations


def save_threshold_outputs(
    threshold_results: pd.DataFrame,
    recommendations: pd.DataFrame,
) -> None:
    """
    Save threshold analysis outputs and plots.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    threshold_results.to_csv(THRESHOLD_ANALYSIS_PATH, index=False)
    recommendations.to_csv(THRESHOLD_RECOMMENDATION_PATH, index=False)

    sns.set_theme(style="whitegrid")

    plt.figure(figsize=(10, 6))
    sns.lineplot(data=threshold_results, x="threshold", y="precision", label="Precision")
    sns.lineplot(data=threshold_results, x="threshold", y="recall", label="Recall")
    sns.lineplot(data=threshold_results, x="threshold", y="f1", label="F1")
    plt.title("Precision, Recall, and F1 by Threshold")
    plt.xlabel("Threshold")
    plt.ylabel("Score")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "threshold_precision_recall_f1.png", dpi=300)
    plt.close()

    plt.figure(figsize=(10, 6))
    sns.lineplot(
        data=threshold_results,
        x="threshold",
        y="customers_flagged",
        label="Customers flagged",
    )
    sns.lineplot(
        data=threshold_results,
        x="threshold",
        y="churners_captured",
        label="Churners captured",
    )
    sns.lineplot(
        data=threshold_results,
        x="threshold",
        y="churners_missed",
        label="Churners missed",
    )
    plt.title("Business Impact by Threshold")
    plt.xlabel("Threshold")
    plt.ylabel("Customer count")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "threshold_business_impact.png", dpi=300)
    plt.close()

    print("\nSaved outputs")
    print("-" * 80)
    print(f"Threshold analysis: {THRESHOLD_ANALYSIS_PATH}")
    print(f"Threshold recommendation: {THRESHOLD_RECOMMENDATION_PATH}")
    print(f"Metrics figure: {FIGURES_DIR / 'threshold_precision_recall_f1.png'}")
    print(f"Business impact figure: {FIGURES_DIR / 'threshold_business_impact.png'}")


def print_threshold_summary(
    threshold_results: pd.DataFrame,
    recommendations: pd.DataFrame,
) -> None:
    """
    Print threshold analysis summary.
    """
    print("=" * 80)
    print("THRESHOLD ANALYSIS")
    print("=" * 80)

    print(f"\nSelected model: {SELECTED_MODEL}")

    print("\nRecommended thresholds")
    display_columns = [
        "strategy",
        "threshold",
        "precision",
        "recall",
        "f1",
        "false_positives",
        "false_negatives",
        "customers_flagged",
        "churners_captured",
        "churners_missed",
        "business_meaning",
    ]

    formatted = recommendations[display_columns].copy()

    for column in ["threshold", "precision", "recall", "f1"]:
        formatted[column] = formatted[column].astype(float).round(4)

    print(formatted)

    print("\nDefault threshold 0.50")
    default_row = threshold_results[
        threshold_results["threshold"].round(2) == 0.50
    ][
        [
            "threshold",
            "accuracy",
            "precision",
            "recall",
            "f1",
            "false_positives",
            "false_negatives",
            "customers_flagged",
            "churners_captured",
            "churners_missed",
        ]
    ]

    print(default_row.round(4))


if __name__ == "__main__":
    validation_predictions = load_validation_predictions()

    threshold_results = evaluate_thresholds(
        predictions=validation_predictions,
        model_name=SELECTED_MODEL,
    )

    recommendations = select_thresholds(threshold_results)

    print_threshold_summary(
        threshold_results=threshold_results,
        recommendations=recommendations,
    )

    save_threshold_outputs(
        threshold_results=threshold_results,
        recommendations=recommendations,
    )